name = "save-and-smile"
compatibility_date = "2024-01-01"
pages_build_output_dir = "."

[vars]
# You can set variables here or inside the Cloudflare Pages Dashboard
# DATABASE_URL = "postgresql://..."
