module.exports = [
`CREATE TABLE IF NOT EXISTS roles (
  id VARCHAR(40) PRIMARY KEY,
  name VARCHAR(80) NOT NULL
)`,
`CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  email VARCHAR(190) UNIQUE NOT NULL,
  name VARCHAR(120) NOT NULL,
  password_hash TEXT NOT NULL,
  role VARCHAR(40) NOT NULL DEFAULT 'admin',
  status VARCHAR(20) NOT NULL DEFAULT 'active',
  created_at TIMESTAMPTZ DEFAULT NOW()
)`,
`CREATE TABLE IF NOT EXISTS sessions (
  id VARCHAR(80) PRIMARY KEY,
  user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  csrf TEXT NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
)`,
`CREATE TABLE IF NOT EXISTS media_folders (
  id SERIAL PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  parent_id INT REFERENCES media_folders(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
)`,
`CREATE TABLE IF NOT EXISTS media (
  id VARCHAR(64) PRIMARY KEY,
  folder_id INT REFERENCES media_folders(id) ON DELETE SET NULL,
  title TEXT,
  alt TEXT,
  caption TEXT,
  description TEXT,
  original_name TEXT,
  mime VARCHAR(80),
  size_bytes INT,
  width INT,
  height INT,
  url TEXT NOT NULL,
  variants JSONB DEFAULT '{}'::jsonb,
  source VARCHAR(20) DEFAULT 'upload',
  created_at TIMESTAMPTZ DEFAULT NOW()
)`,
`CREATE TABLE IF NOT EXISTS brands (
  id SERIAL PRIMARY KEY,
  name VARCHAR(160) NOT NULL,
  slug VARCHAR(160) UNIQUE NOT NULL,
  logo_media_id VARCHAR(64) REFERENCES media(id) ON DELETE SET NULL,
  description TEXT,
  status VARCHAR(20) DEFAULT 'active',
  seo JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW()
)`,
`CREATE TABLE IF NOT EXISTS categories (
  id VARCHAR(80) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  slug VARCHAR(160) UNIQUE NOT NULL,
  parent_id VARCHAR(80),
  icon TEXT,
  image_media_id VARCHAR(64) REFERENCES media(id) ON DELETE SET NULL,
  banner_media_id VARCHAR(64) REFERENCES media(id) ON DELETE SET NULL,
  description TEXT,
  sort_order INT DEFAULT 0,
  status VARCHAR(20) DEFAULT 'active',
  featured BOOLEAN DEFAULT false,
  seo JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW()
)`,
`CREATE TABLE IF NOT EXISTS collections (
  id SERIAL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  slug VARCHAR(160) UNIQUE NOT NULL,
  type VARCHAR(20) DEFAULT 'manual',
  description TEXT,
  image_media_id VARCHAR(64) REFERENCES media(id) ON DELETE SET NULL,
  conditions JSONB DEFAULT '{}'::jsonb,
  sort_mode VARCHAR(40) DEFAULT 'manual',
  status VARCHAR(20) DEFAULT 'published',
  seo JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW()
)`,
`CREATE TABLE IF NOT EXISTS products (
  id SERIAL PRIMARY KEY,
  title TEXT NOT NULL,
  slug VARCHAR(180) UNIQUE NOT NULL,
  sku VARCHAR(100),
  barcode VARCHAR(100),
  description TEXT,
  short_description TEXT,
  category_id VARCHAR(80) REFERENCES categories(id) ON DELETE SET NULL,
  tab VARCHAR(80),
  brand_id INT REFERENCES brands(id) ON DELETE SET NULL,
  tags TEXT,
  price NUMERIC(12,2) NOT NULL DEFAULT 0,
  compare_price NUMERIC(12,2),
  cost_price NUMERIC(12,2),
  tax_rate NUMERIC(6,2) DEFAULT 0,
  stock INT DEFAULT 0,
  low_stock INT DEFAULT 5,
  weight_grams NUMERIC(10,2),
  length_cm NUMERIC(10,2),
  width_cm NUMERIC(10,2),
  height_cm NUMERIC(10,2),
  status VARCHAR(20) DEFAULT 'published',
  featured BOOLEAN DEFAULT false,
  badge VARCHAR(50),
  rating NUMERIC(3,2) DEFAULT 4.8,
  reviews_count INT DEFAULT 0,
  featured_media_id VARCHAR(64) REFERENCES media(id) ON DELETE SET NULL,
  video_url TEXT,
  video_meta JSONB DEFAULT '{}'::jsonb,
  related_ids JSONB DEFAULT '[]'::jsonb,
  cross_sell_ids JSONB DEFAULT '[]'::jsonb,
  upsell_ids JSONB DEFAULT '[]'::jsonb,
  seo JSONB DEFAULT '{}'::jsonb,
  specs JSONB DEFAULT '{}'::jsonb,
  published_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
)`,
`CREATE TABLE IF NOT EXISTS product_images (
  id SERIAL PRIMARY KEY,
  product_id INT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  media_id VARCHAR(64) REFERENCES media(id) ON DELETE SET NULL,
  alt TEXT,
  sort_order INT DEFAULT 0
)`,
`CREATE TABLE IF NOT EXISTS product_variants (
  id SERIAL PRIMARY KEY,
  product_id INT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  title VARCHAR(160),
  sku VARCHAR(100),
  barcode VARCHAR(100),
  options JSONB DEFAULT '{}'::jsonb,
  price NUMERIC(12,2),
  compare_price NUMERIC(12,2),
  cost_price NUMERIC(12,2),
  stock INT DEFAULT 0,
  weight_grams NUMERIC(10,2),
  media_id VARCHAR(64) REFERENCES media(id) ON DELETE SET NULL,
  status VARCHAR(20) DEFAULT 'active'
)`,
`CREATE TABLE IF NOT EXISTS collection_products (
  collection_id INT NOT NULL REFERENCES collections(id) ON DELETE CASCADE,
  product_id INT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  sort_order INT DEFAULT 0,
  PRIMARY KEY (collection_id, product_id)
)`,
`CREATE TABLE IF NOT EXISTS inventory_movements (
  id SERIAL PRIMARY KEY,
  product_id INT REFERENCES products(id) ON DELETE SET NULL,
  variant_id INT REFERENCES product_variants(id) ON DELETE SET NULL,
  delta INT NOT NULL,
  reason VARCHAR(80),
  note TEXT,
  user_id INT REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
)`,
`CREATE TABLE IF NOT EXISTS customers (
  id SERIAL PRIMARY KEY,
  name VARCHAR(160) NOT NULL,
  phone VARCHAR(40) UNIQUE NOT NULL,
  email VARCHAR(160),
  status VARCHAR(20) DEFAULT 'active',
  customer_group VARCHAR(40) DEFAULT 'retail',
  notes TEXT,
  total_spent NUMERIC(12,2) DEFAULT 0,
  order_count INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
)`,
`CREATE TABLE IF NOT EXISTS customer_addresses (
  id SERIAL PRIMARY KEY,
  customer_id INT NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  city VARCHAR(80),
  area VARCHAR(120),
  address TEXT,
  landmark TEXT,
  is_default BOOLEAN DEFAULT true
)`,
`CREATE TABLE IF NOT EXISTS orders (
  id SERIAL PRIMARY KEY,
  order_code VARCHAR(50) UNIQUE NOT NULL,
  customer_id INT REFERENCES customers(id) ON DELETE SET NULL,
  customer_name VARCHAR(255) NOT NULL,
  customer_phone VARCHAR(50) NOT NULL,
  customer_email VARCHAR(160),
  customer_address TEXT NOT NULL,
  customer_city VARCHAR(100) NOT NULL,
  area VARCHAR(120),
  landmark TEXT,
  delivery_notes TEXT,
  payment_method VARCHAR(50) DEFAULT 'COD',
  payment_status VARCHAR(30) DEFAULT 'unpaid',
  coupon_code VARCHAR(40),
  discount_amount NUMERIC(12,2) DEFAULT 0,
  subtotal NUMERIC(12,2) NOT NULL,
  shipping_fee NUMERIC(12,2) DEFAULT 0,
  tax_amount NUMERIC(12,2) DEFAULT 0,
  grand_total NUMERIC(12,2) NOT NULL,
  status VARCHAR(50) DEFAULT 'Pending',
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
)`,
`CREATE TABLE IF NOT EXISTS order_items (
  id SERIAL PRIMARY KEY,
  order_id INT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  product_id INT,
  variant_id INT,
  title TEXT NOT NULL,
  sku VARCHAR(80),
  price NUMERIC(12,2) NOT NULL,
  qty INT NOT NULL,
  total NUMERIC(12,2) NOT NULL
)`,
`CREATE TABLE IF NOT EXISTS order_events (
  id SERIAL PRIMARY KEY,
  order_id INT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  status VARCHAR(50) NOT NULL,
  note TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
)`,
`CREATE TABLE IF NOT EXISTS reviews (
  id SERIAL PRIMARY KEY,
  product_id INT REFERENCES products(id) ON DELETE SET NULL,
  customer_name VARCHAR(120) NOT NULL,
  rating INT NOT NULL,
  title TEXT,
  body TEXT,
  image_url TEXT,
  video_url TEXT,
  verified BOOLEAN DEFAULT false,
  featured BOOLEAN DEFAULT false,
  status VARCHAR(20) DEFAULT 'approved',
  color VARCHAR(20),
  created_at TIMESTAMPTZ DEFAULT NOW()
)`,
`CREATE TABLE IF NOT EXISTS coupons (
  id SERIAL PRIMARY KEY,
  code VARCHAR(40) UNIQUE NOT NULL,
  type VARCHAR(30) NOT NULL,
  value NUMERIC(12,2) NOT NULL DEFAULT 0,
  min_order NUMERIC(12,2) DEFAULT 0,
  max_discount NUMERIC(12,2),
  product_ids JSONB DEFAULT '[]'::jsonb,
  category_ids JSONB DEFAULT '[]'::jsonb,
  collection_ids JSONB DEFAULT '[]'::jsonb,
  usage_limit INT,
  per_customer_limit INT DEFAULT 1,
  used_count INT DEFAULT 0,
  first_order_only BOOLEAN DEFAULT false,
  free_shipping BOOLEAN DEFAULT false,
  starts_at TIMESTAMPTZ,
  ends_at TIMESTAMPTZ,
  status VARCHAR(20) DEFAULT 'active'
)`,
`CREATE TABLE IF NOT EXISTS coupon_redemptions (
  id SERIAL PRIMARY KEY,
  coupon_id INT REFERENCES coupons(id) ON DELETE CASCADE,
  customer_phone VARCHAR(40),
  order_id INT,
  created_at TIMESTAMPTZ DEFAULT NOW()
)`,
`CREATE TABLE IF NOT EXISTS banners (
  id SERIAL PRIMARY KEY,
  title TEXT,
  subtitle TEXT,
  cta TEXT,
  url TEXT,
  desktop_media_id VARCHAR(64) REFERENCES media(id) ON DELETE SET NULL,
  mobile_media_id VARCHAR(64) REFERENCES media(id) ON DELETE SET NULL,
  image_url TEXT,
  start_at TIMESTAMPTZ,
  end_at TIMESTAMPTZ,
  status VARCHAR(20) DEFAULT 'published',
  sort_order INT DEFAULT 0
)`,
`CREATE TABLE IF NOT EXISTS reels (
  id SERIAL PRIMARY KEY,
  title TEXT,
  price NUMERIC(12,2),
  compare_price NUMERIC(12,2),
  code VARCHAR(80),
  video_url TEXT,
  thumb_url TEXT,
  product_id INT REFERENCES products(id) ON DELETE SET NULL,
  sort_order INT DEFAULT 0,
  status VARCHAR(20) DEFAULT 'published'
)`,
`CREATE TABLE IF NOT EXISTS pages (
  id SERIAL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  slug VARCHAR(160) UNIQUE NOT NULL,
  type VARCHAR(40) DEFAULT 'page',
  status VARCHAR(20) DEFAULT 'draft',
  published_version_id INT,
  seo JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
)`,
`CREATE TABLE IF NOT EXISTS page_versions (
  id SERIAL PRIMARY KEY,
  page_id INT NOT NULL REFERENCES pages(id) ON DELETE CASCADE,
  label VARCHAR(80),
  sections JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_by INT REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
)`,
`CREATE TABLE IF NOT EXISTS settings (
  key VARCHAR(80) PRIMARY KEY,
  value JSONB NOT NULL
)`,
`CREATE TABLE IF NOT EXISTS redirects (
  id SERIAL PRIMARY KEY,
  from_path VARCHAR(255) UNIQUE NOT NULL,
  to_path VARCHAR(255) NOT NULL,
  status_code INT DEFAULT 301
)`,
`CREATE TABLE IF NOT EXISTS forms (
  id SERIAL PRIMARY KEY,
  name VARCHAR(160) NOT NULL,
  slug VARCHAR(160) UNIQUE NOT NULL,
  fields JSONB NOT NULL DEFAULT '[]'::jsonb,
  status VARCHAR(20) DEFAULT 'active'
)`,
`CREATE TABLE IF NOT EXISTS form_submissions (
  id SERIAL PRIMARY KEY,
  form_id INT REFERENCES forms(id) ON DELETE CASCADE,
  payload JSONB NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
)`,
`CREATE TABLE IF NOT EXISTS popups (
  id SERIAL PRIMARY KEY,
  title VARCHAR(160) NOT NULL,
  type VARCHAR(40) DEFAULT 'promo',
  content JSONB DEFAULT '{}'::jsonb,
  pages JSONB DEFAULT '[]'::jsonb,
  delay_seconds INT DEFAULT 0,
  status VARCHAR(20) DEFAULT 'draft',
  desktop_only BOOLEAN DEFAULT false,
  mobile_only BOOLEAN DEFAULT false
)`,
`CREATE TABLE IF NOT EXISTS shipping_zones (
  id SERIAL PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  cities JSONB DEFAULT '[]'::jsonb,
  flat_rate NUMERIC(12,2) DEFAULT 200,
  free_threshold NUMERIC(12,2),
  cod_charge NUMERIC(12,2) DEFAULT 0,
  eta_days VARCHAR(40),
  status VARCHAR(20) DEFAULT 'active'
)`,
`CREATE TABLE IF NOT EXISTS wishlists (
  id SERIAL PRIMARY KEY,
  customer_phone VARCHAR(40),
  product_id INT REFERENCES products(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW()
)`,
`CREATE INDEX IF NOT EXISTS idx_products_status ON products(status)`,
`CREATE INDEX IF NOT EXISTS idx_products_category ON products(category_id)`,
`CREATE INDEX IF NOT EXISTS idx_orders_code ON orders(order_code)`,
`CREATE INDEX IF NOT EXISTS idx_orders_phone ON orders(customer_phone)`,
`CREATE INDEX IF NOT EXISTS idx_media_created ON media(created_at DESC)`
];
